apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: webycash-afxdp
  namespace: webycash
  annotations:
    k8s.v1.cni.cncf.io/resourceName: afxdp/webycashPool
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "afxdp",
      "mode": "primary",
      "logFile": "afxdp-cni.log",
      "logLevel": "info",
      "ipam": {
        "type": "host-local",
        "subnet": "10.244.0.0/16",
        "routes": [{ "dst": "0.0.0.0/0" }]
      }
    }'
