//! Pure transition functions.
//!
//! Every transition is a free function (no `&mut self`) of shape
//! `fn (SwapState<A>, …) -> Result<SwapState<B>>`. The prior phase is
//! consumed; the next phase is constructed from its fields plus whatever
//! new inputs the transition needs.
//!
//! The transitions do NOT call out to external services themselves —
//! they take the *result* of the external call as an input. This keeps
//! the typestate layer pure and trivial to unit-test; the orchestrator
//! in `api/` is the only place that calls webcash.org / RGB-server / push
//! provider, then folds the answer into a transition.

use std::marker::PhantomData as Pd;

use super::phases::*;
use super::types::*;
use crate::error::{RefereeError, Result};

/// Build the initial state from the inbound `/v1/swap/initiate` payload.
///
/// Pure: no I/O, no clocks, no randomness. Caller supplies `id`, `now_unix`
/// and the new audit tip — `id` is generated by the orchestrator before the
/// audit log is touched, so the audit "init" entry already commits to it.
#[allow(clippy::too_many_arguments)]
pub fn initiate(
    id: SwapId,
    parties: Parties,
    bob: BobPayload,
    alice: AlicePayload,
    alice_nonces: AliceMusig2Nonces,
    referee_sessions: Musig2Sessions,
    now_unix: u64,
    audit_tip_hex: String,
) -> SwapState<SwapInit> {
    SwapState {
        id,
        parties,
        bob,
        alice,
        alice_nonces,
        referee_sessions,
        phase_entered_at: now_unix,
        insert_push_attempts: 0,
        audit_tip_hex,
        _phase: Pd,
    }
}

/// Mark both ZKPs as verified. Caller pre-runs the Groth16 verifier and
/// hands the boolean outcome via `outcomes_ok`. Misuse (passing `false`)
/// is rejected explicitly so the type system can't be tricked into
/// constructing a `ZkpsVerified` from un-verified inputs.
pub fn verify_zkps(
    s: SwapState<SwapInit>,
    outcomes_ok: bool,
    now_unix: u64,
    new_audit_tip: String,
) -> Result<SwapState<ZkpsVerified>> {
    if !outcomes_ok {
        return Err(RefereeError::ZkpRejected(
            "one of the ZKPs failed verification".into(),
        ));
    }
    Ok(advance(s, now_unix, new_audit_tip))
}

/// Record the pre-check result. The orchestrator calls webcash.org's
/// `/health_check`; here we only consume the boolean.
pub fn pre_check(
    s: SwapState<ZkpsVerified>,
    h_b_unspent: bool,
    now_unix: u64,
    new_audit_tip: String,
) -> Result<SwapState<PreChecked>> {
    if !h_b_unspent {
        return Err(RefereeError::InvalidTransition(
            "pre-check: H_B already spent — refusing to start swap".into(),
        ));
    }
    Ok(advance(s, now_unix, new_audit_tip))
}

/// Record that the insert-push was dispatched. Consumes the prior
/// `PreChecked` (or, on retry, another `InsertPushed`) and increments
/// the attempt counter.
pub fn insert_pushed_from_pre(
    s: SwapState<PreChecked>,
    now_unix: u64,
    new_audit_tip: String,
) -> SwapState<InsertPushed> {
    let mut next = advance(s, now_unix, new_audit_tip);
    next.insert_push_attempts = 1;
    next
}

/// Retry the push: consumes a prior `InsertPushed` and produces a new
/// one with the attempt counter bumped.
pub fn insert_pushed_retry(
    mut s: SwapState<InsertPushed>,
    now_unix: u64,
    new_audit_tip: String,
) -> Result<SwapState<InsertPushed>> {
    s.insert_push_attempts =
        s.insert_push_attempts.checked_add(1).ok_or_else(|| {
            RefereeError::InvalidTransition("insert_push_attempts overflow".into())
        })?;
    s.phase_entered_at = now_unix;
    s.audit_tip_hex = new_audit_tip;
    Ok(s)
}

/// Outcome of the post-check, which determines whether settlement
/// proceeds (`spent`) or the swap is aborted (`unspent` + retries
/// exhausted).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PostCheckOutcome {
    /// `H_B` is now spent — Alice took ownership. Proceed to `Settled`.
    Settled,
    /// `H_B` is still unspent. Caller must decide retry vs abort based
    /// on `insert_push_attempts` vs the configured limit.
    StillUnspent,
}

/// Settled-success transition: `H_B` is spent on webcash.org.
pub fn settle(
    s: SwapState<InsertPushed>,
    outcome: PostCheckOutcome,
    now_unix: u64,
    new_audit_tip: String,
) -> Result<SwapState<Settled>> {
    if outcome != PostCheckOutcome::Settled {
        return Err(RefereeError::InvalidTransition(
            "settle: post-check still shows H_B unspent".into(),
        ));
    }
    Ok(advance(s, now_unix, new_audit_tip))
}

/// Abort: post-check shows still-unspent AND retries exhausted. Produces
/// an `Aborted` state which is the precondition for `invalidate_push`.
pub fn abort(
    s: SwapState<InsertPushed>,
    retries_exhausted: bool,
    now_unix: u64,
    new_audit_tip: String,
) -> Result<SwapState<Aborted>> {
    if !retries_exhausted {
        return Err(RefereeError::InvalidTransition(
            "abort: more retries are still available — must retry first".into(),
        ));
    }
    Ok(advance(s, now_unix, new_audit_tip))
}

/// Bob's wallet acked the `invalidate_hook` push.
pub fn invalidated(
    s: SwapState<Aborted>,
    bob_acked: bool,
    now_unix: u64,
    new_audit_tip: String,
) -> Result<SwapState<Invalidated>> {
    if !bob_acked {
        return Err(RefereeError::InvalidTransition(
            "invalidated: Bob's wallet did not ack the invalidate_hook".into(),
        ));
    }
    Ok(advance(s, now_unix, new_audit_tip))
}

/// Refund-sig sent to Alice. Terminal.
pub fn refunded(
    s: SwapState<Invalidated>,
    now_unix: u64,
    new_audit_tip: String,
) -> SwapState<Refunded> {
    advance(s, now_unix, new_audit_tip)
}

// ─────────────────────────────────────────────────────────────────────────────
// Phase-erasing helper
// ─────────────────────────────────────────────────────────────────────────────

fn advance<A: Phase, B: Phase>(
    s: SwapState<A>,
    now_unix: u64,
    new_audit_tip: String,
) -> SwapState<B> {
    SwapState {
        id: s.id,
        parties: s.parties,
        bob: s.bob,
        alice: s.alice,
        alice_nonces: s.alice_nonces,
        referee_sessions: s.referee_sessions,
        phase_entered_at: now_unix,
        insert_push_attempts: s.insert_push_attempts,
        audit_tip_hex: new_audit_tip,
        _phase: Pd,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn parties() -> Parties {
        Parties {
            bob_pgp_fp: PgpFingerprint("aa".repeat(20)),
            bob_pgp_pubkey_hex: "bb".repeat(64),
            alice_pgp_fp: PgpFingerprint("cc".repeat(20)),
            alice_pgp_pubkey_hex: "dd".repeat(64),
            alice_musig2_pubkey: Secp256k1Pubkey("02".to_string() + &"ee".repeat(32)),
        }
    }

    fn bob() -> BobPayload {
        BobPayload {
            h_b: WebcashPublicHash::new("h".repeat(64)),
            enc_secret_for_alice: PgpEncrypted::new(b"ciphertext-bob".to_vec()),
            zkp_payload: Groth16Proof {
                proof: vec![1, 2, 3],
                public_inputs: vec![vec![0xa]],
            },
        }
    }

    fn alice() -> AlicePayload {
        AlicePayload {
            vtxo: ArkOutpointHash("v".repeat(64)),
            tx_settle_hash: "s".repeat(64),
            tx_refund_hash: "r".repeat(64),
            enc_partial_sig_for_bob: PgpEncrypted::new(b"ciphertext-alice".to_vec()),
            zkp_signature: Groth16Proof {
                proof: vec![4, 5, 6],
                public_inputs: vec![vec![0xb]],
            },
        }
    }

    fn nonces() -> AliceMusig2Nonces {
        AliceMusig2Nonces {
            settle_nonce_pub: "11".repeat(66),
            refund_nonce_pub: "22".repeat(66),
        }
    }

    fn sessions(handle: SwapId) -> Musig2Sessions {
        Musig2Sessions {
            settle_pub_nonce: "33".repeat(66),
            refund_pub_nonce: "44".repeat(66),
            secret_nonce_handle: handle,
        }
    }

    fn fresh_init() -> SwapState<SwapInit> {
        let id = SwapId::fresh();
        SwapState {
            id: id.clone(),
            parties: parties(),
            bob: bob(),
            alice: alice(),
            alice_nonces: nonces(),
            referee_sessions: sessions(id),
            phase_entered_at: 1000,
            insert_push_attempts: 0,
            audit_tip_hex: "00".repeat(32),
            _phase: Pd,
        }
    }

    #[test]
    fn happy_path_init_to_settled() {
        let s = fresh_init();
        let s = verify_zkps(s, true, 1001, "01".repeat(32)).unwrap();
        let s = pre_check(s, true, 1002, "02".repeat(32)).unwrap();
        let s = insert_pushed_from_pre(s, 1003, "03".repeat(32));
        let s = settle(s, PostCheckOutcome::Settled, 1004, "04".repeat(32)).unwrap();
        assert_eq!(s.audit_tip_hex, "04".repeat(32));
        assert_eq!(SwapState::<Settled>::PHASE_NAME, "settled");
    }

    #[test]
    fn abort_path_drives_invalidated_then_refunded() {
        let s = fresh_init();
        let s = verify_zkps(s, true, 1, "a".repeat(64)).unwrap();
        let s = pre_check(s, true, 2, "b".repeat(64)).unwrap();
        let s = insert_pushed_from_pre(s, 3, "c".repeat(64));
        let s = insert_pushed_retry(s, 4, "d".repeat(64)).unwrap();
        let s = insert_pushed_retry(s, 5, "e".repeat(64)).unwrap();
        assert_eq!(s.insert_push_attempts, 3);
        let s = abort(s, true, 6, "f".repeat(64)).unwrap();
        let s = invalidated(s, true, 7, "10".repeat(32)).unwrap();
        let s = refunded(s, 8, "11".repeat(32));
        assert_eq!(SwapState::<Refunded>::PHASE_NAME, "refunded");
        let _ = s.audit_tip_hex;
    }

    #[test]
    fn verify_zkps_rejects_when_not_ok() {
        let s = fresh_init();
        let err = verify_zkps(s, false, 1, "x".repeat(64)).unwrap_err();
        assert!(matches!(err, RefereeError::ZkpRejected(_)));
    }

    #[test]
    fn pre_check_rejects_already_spent() {
        let s = fresh_init();
        let s = verify_zkps(s, true, 1, "x".repeat(64)).unwrap();
        let err = pre_check(s, false, 2, "y".repeat(64)).unwrap_err();
        assert!(matches!(err, RefereeError::InvalidTransition(_)));
    }

    #[test]
    fn settle_rejects_unspent_outcome() {
        let s = fresh_init();
        let s = verify_zkps(s, true, 1, "a".repeat(64)).unwrap();
        let s = pre_check(s, true, 2, "b".repeat(64)).unwrap();
        let s = insert_pushed_from_pre(s, 3, "c".repeat(64));
        let err = settle(s, PostCheckOutcome::StillUnspent, 4, "d".repeat(64)).unwrap_err();
        assert!(matches!(err, RefereeError::InvalidTransition(_)));
    }

    #[test]
    fn abort_rejects_when_retries_remain() {
        let s = fresh_init();
        let s = verify_zkps(s, true, 1, "a".repeat(64)).unwrap();
        let s = pre_check(s, true, 2, "b".repeat(64)).unwrap();
        let s = insert_pushed_from_pre(s, 3, "c".repeat(64));
        let err = abort(s, false, 4, "d".repeat(64)).unwrap_err();
        assert!(matches!(err, RefereeError::InvalidTransition(_)));
    }
}
